### ISSUE TITLE
Criar app factory para a aplicação

### ISSUE THREAD

**Issue by MarcelFox** [LuisRachope/FlaskApiRest#1]
# Contexto
A aplicação precisa ter uma app factory para ser mais flexível, de forma que seja possível exportar o contexto _app_ para outras partes do código. Existe a [documentação de app factories](https://flask.palletsprojects.com/en/2.3.x/patterns/appfactories/) que pode ser útil nessa issue.

**Comment by LuisRachope** [comment]
Foi refatorado o código para tornar ele em um app factory e também adicionamos padrões de desenvolvimento para torna-lo mais legível e flexível. Precisando estou à disposição!
